### ISSUE TITLE
Feedback on example?

### ISSUE THREAD

**Issue by sdwfrost** [AlgebraicJulia/AlgebraicDynamics.jl#40]
Hi @jpfairbanks @slibkind 

I'm trying to write an example of my [standard SIR model](https://github.com/epirecipes/sir-julia) plus some extensions using AlgebraicDynamics.jl. [Here's a gist of what I have so far](https://gist.github.com/sdwfrost/1344bffed41a5ab3754cde42918de796) - I would be keen to get input before putting it up, as I don't want to provide a poor implementation. In particular, it would be nice to have the 'method of stages' (where one has a number of artificial stages arranged in serial and/or parallel) presented in a nicer way - possibly as a machine with the wiring done as a loop so as to add an arbitrary number of stages?

**Comment by jpfairbanks** [comment]
Thanks for including us @sdwfrost! Is there a way to preview that markdown with output?

About adding multiple stages with a loop, you could do it with a regular julia program rather than putting a loop in the diagram. You can construct an UndirectedWiringDiagram or For example, you can do 

```julia
d = @relation (S, I) begin
    si_infection(S,I₁)
end

add_box!(d, 2, name="inf2")
add_junction!(d, variable=:I2)
add_wire!(d, 1, 2)
```
or something like that. The relation macro is just a syntactic sugar for a constructor of the `UntypedRelationDiagram` or  `TypedRelationDiagram`. Those constructors build julia structs that you can manipulate with these functions like `add_box!, add_wire!, add_junction!`

The relevant areas of the source code are in:
1. https://github.com/AlgebraicJulia/Catlab.jl/blob/master/src/wiring_diagrams/Undirected.jl
2. https://github.com/AlgebraicJulia/Catlab.jl/blob/master/src/wiring_diagrams/MonoidalUndirected.jl
3. https://github.com/AlgebraicJulia/Catlab.jl/blob/master/src/programs/RelationalPrograms.jl

**Comment by jpfairbanks** [comment]
Also have you seen https://algebraicjulia.github.io/AlgebraicPetri.jl/dev/examples/covid/coexist/coexist/?

**Comment by sdwfrost** [comment]
Thanks @jpfairbanks! I added the example (which is the simplest way to share a rendered Markdown: [https://github.com/epirecipes/sir-julia/blob/master/markdown/ode_algebraicdynamics/ode_algebraicdynamics.md](https://github.com/epirecipes/sir-julia/blob/master/markdown/ode_algebraicdynamics/ode_algebraicdynamics.md)

I'll look through the code. I've seen @mehalter COEXIST example (and Micah was kind enough to contribute an AlgebraicPetri.jl example [here](https://github.com/epirecipes/sir-julia/blob/master/markdown/pn_algebraicpetri/pn_algebraicpetri.md). I'm still trying to get my head around the relationship between this package and AlgebraicPetri.jl.

**Comment by slibkind** [comment]
Hi @sdwfrost! I took a look through your code and it's a great use of AlgebraicDynamics! All the implementations look good to me.

I had a few ideas for using some additional features to simplify your final _method of stages_  example. I'll share them below.

**Comment by slibkind** [comment]
First you can use dictionaries keyed by the box name to specify which resource sharers plug into which box. 

So instead of 
```julia
undirected_system_stages = oapply(undirected_pattern_stages, [
    si_infection
    sii_infection
    sii_infection
    sii_infection
    i_transition
    i_transition
    i_transition
    ilast_recovery])
```
you can write
```julia
undirected_system_stages = oapply(undirected_pattern_stages, Dict(
    :si_infection  => si_infection, 
    :sii_infection => sii_infection,
    :i_transition  => i_transition,
    :ilast_recovery => ilast_recovery
))
```
This is also nice because you don't have to worry about the box order.

**Comment by slibkind** [comment]
Another feature is that you can build out a composition pattern hierarchically. For example, we can start out with a pattern with two boxes 

1. A `si_box` that we will put all of the infection boxes inside
2. A `i_box` that we will put all of the transition boxes inside

```julia
undirected_SI_pattern = @relation (S, I₁, I₂, I₃, I₄) begin
    si_box(S, I₁, I₂, I₃, I₄)
    i_box(I₁, I₂, I₃, I₄)
end
```

Then we can build patterns to put inside of these boxes:
```julia
si_pattern = @relation (S, I₁, I₂, I₃, I₄) begin
    si_infection(S,I₁)
    sii_infection(S,I₁,I₂)
    sii_infection(S,I₁,I₃)
    sii_infection(S,I₁,I₄)
end

i_pattern = @relation (I₁, I₂, I₃, I₄) begin
    i_transition(I₁,I₂)
    i_transition(I₂,I₃)
    i_transition(I₃,I₄)
    ilast_recovery(I₄)
end
```

And finally we put the patterns inside of the boxes using `ocompose`.
```julia
undirected_pattern_stages = ocompose(undirected_SI_pattern, [si_pattern, i_pattern])
```

One thing I like about this strategy is that it lets you inspect each of the component patterns individually instead of the big web at the end.

**Comment by slibkind** [comment]
> I'm still trying to get my head around the relationship between this package and AlgebraicPetri.jl.

I believe that there is functor between AlgebraicPetri and AlgebraicDynamics. It's on my to-do list to implement it!

**Comment by jpfairbanks** [comment]
Thanks @slibkind for such great answers for @sdwfrost!

> I'm still trying to get my head around the relationship between this package and AlgebraicPetri.jl.

As @slibkind said, there is a functor from Petri Nets to Dynamical Systems that encodes the Law of Mass Action. It is implemented "by hand" in Algebraic Petri, but Sophie has on the roadmap a more general implementation of which that would be an example.

I think that AlgebraicPetri will support other operations that you can do with Petri Nets that don't make sense for general dynamical systems. For example, there are token passing semantics for Petri Nets that are relevant for using Petri Nets as a model of parallel computation. That kind of formal methods for parallel computing functionality would go in AlgebraicPetri and not AlgebraicDynamics. Also there are other classes of dynamical systems that should have functors into AlgebraicDynamics but provide additional functionality (we haven't developed any yet, but if we did, they would also have a standalone package).

**Comment by jpfairbanks** [comment]
@sdwfrost I'm not sure how you are rendering that markdown to HTML, but these Unicode graphics could be HTML <tables> if you tell PtrettyTables.jl that the output is HTML formatted.

```
CSet with elements Box = 1:2, Port = 1:2, Wire = 1:2, OuterPort = 1:0
┌──────┬─────┐
│ Port │ box │
├──────┼─────┤
│    1 │   1 │
│    2 │   2 │
└──────┴─────┘
┌──────┬─────┬─────┐
│ Wire │ src │ tgt │
├──────┼─────┼─────┤
│    1 │   1 │   2 │
│    2 │   2 │   1 │
└──────┴─────┴─────┘
```

**Comment by jpfairbanks** [comment]
They look good on https://www.algebraicjulia.org/blog/post/2020/09/cset-graphs-1/

**Comment by sdwfrost** [comment]
Thanks for all the feedback @slibkind @jpfairbanks! Current version is [here](https://github.com/epirecipes/sir-julia/blob/master/markdown/ode_algebraicdynamics/ode_algebraicdynamics.md) - closing for now.
